name: Selenium Tests CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome-debug:latest
        ports:
          - 4444:4444
          - 5900:5900
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build and run tests using docker-compose
        run: |
          docker-compose up --build -d selenium
          sleep 15 # wait for selenium to be ready
          docker-compose run --rm test-runner gradle clean test
          docker-compose down

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/test
